# Generated by Django 5.0.4 on 2024-04-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.IntegerField(unique=True)),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog')),
                ('name', models.CharField(max_length=280, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='branch')),
                ('name', models.CharField(max_length=280, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.IntegerField(unique=True)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='Enquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=280)),
                ('email', models.CharField(max_length=280)),
                ('number', models.IntegerField(unique=True)),
                ('message', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='gallerys')),
            ],
            options={
                'ordering': ('image',),
            },
        ),
        migrations.CreateModel(
            name='Homes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homes')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='package')),
                ('price', models.IntegerField()),
                ('cont1', models.CharField(max_length=300)),
                ('cont2', models.CharField(max_length=300)),
                ('cont3', models.CharField(max_length=300)),
                ('cont4', models.CharField(max_length=300)),
                ('cont5', models.CharField(max_length=300)),
                ('cont6', models.CharField(max_length=300)),
                ('cont7', models.CharField(blank=True, max_length=300)),
                ('cont8', models.CharField(blank=True, max_length=300)),
                ('cont9', models.CharField(blank=True, max_length=300)),
                ('cont10', models.CharField(blank=True, max_length=300)),
                ('cont11', models.CharField(blank=True, max_length=300)),
                ('cont12', models.CharField(blank=True, max_length=300)),
                ('cont13', models.CharField(blank=True, max_length=300)),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Testi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('detail', models.CharField(max_length=280)),
                ('place', models.CharField(max_length=150)),
            ],
        ),
    ]
